
baseURL = "http://example.org/"
languageCode = "es-es"
title = "Barnes and Boveri | Estructuras Civiles"
theme = "barnes-hugo"

[menu]


  [[menu.header]]
    weight = 2
    name = "Estructuras civiles"
    url = "#services"
  [[menu.header]]
    weight = 3
    name = "Bussiness & Corporate"
    url = "#pricing"
  [[menu.header]]
    weight = 4
    name = "Sobre Nosotros"
    url = "#about-us"
  [[menu.header]]
    weight = 5
    name = "Proyectos"
    url = "#portfolio"
  [[menu.header]]
    weight = 6
    name = "Contacto"
    url = "#contact"


  [[menu.footer]]
    weight = 2
    name = "Estructuras civiles"
    url = "#services"
  [[menu.footer]]
    weight = 3
    name = "Bussiness & Corporate"
    url = "#pricing"
  [[menu.footer]]
    weight = 4
    name = "Sobre Nosotros"
    url = "#about-us"
  [[menu.footer]]
    weight = 5
    name = "Proyectos"
    url = "#portfolio"
  [[menu.footer]]
    weight = 6
    name = "Contacto"
    url = "#contact"

[params]

  [params.slider]
    enable = true
    title = "OUTSOURCING TÉCNICO enfocado al negocio"
    subtitle = "Ofrecemos servicios personalizados de ingeniería civil prestados por los mayores expertos del mercado en soluciones estructurales."

  [params.estructuras]
    enable = true
    title = "Estructuras Civiles"
    subtitle = "Ingenier&iacute;a multidisciplinar"
    paragraph1 = "Estructuras civiles una empresa de Ingeniería multidisciplinar compuesta por Ingenieros Industriales con una dilatada trayectoria profesional, con más de 20 años de experiencia trabajando en el sector de la construcción y en el sector industrial."
    paragraph2 = "Les ofrecemos nuestros servicios personalizados de ingeniería y consultoría técnica y empresarial, tanto a nivel nacional como internacional y nuestro objetivo prioritario es proporcionar estos servicios con la mayor calidad y cumpliendo rigurosamente con los hitos marcados por nuestros clientes, estableciendo con ellos una relación basada en la confianza y el compromiso."

  [params.estructuras.punto1]
    enable = true
    title = "ASESORAMIENTO TÉCNICO Y CONSULTORÍA"
    point1 = "Estudios previos: bocetos y estudio económico"
    point2 = "Revisión de proyectos"
    point3 = "Dimensionamiento estructura"
    point4 = "Estudios comparativos y de optimización"
    point5 = "Informes técnicos y periciales"
    point6 = "Planos de taller y diseño de moldes"
    point7 = "Dirección de obra y asistencia técnica"

  [params.estructuras.punto2]
    enable = true
    title = "CALCULO DE ESTRUCTURAS E INSTALACIONES"
    point1 = "Documentación de proyectos: memoria, cálculos y planos."
    point2 = "Estructura metálica y hormigón, tanto de edificios nuevos como rehabilitaciones."
    point3 = "Edificación Residencial, Edificación Industrial, Obra Pública, Obra Arquitectónica y Obra Marina."

  [params.estructuras.punto3]
    enable = true
    title = "GESTIÓN INTEGRAL DE PROYECTOS"
    point1 = "Realización de proyecto completo."
    point2 = "Búsqueda de terrenos."
    point3 = "Obtención de licencias y permisos."
    point4 = "Compra de maquinaria y bienes de equipo."
    point5 = "Implantación y puesta en marcha."

  [params.estructuras.punto4]
    enable = true
    title = "TRABAJOS DE CAMPO TERRITORIO NACIONAL E INTERNACIONAL"
    paragraph = "Realizamos la inspección de patologías en elementos y hacemos la toma de datos para la realización de informes y documentación, tanto a nivel nacional como internacional."

  [params.estructuras.punto5]
    enable = true
    title = "AGENTES COMERCIALES"
    paragraph = "Llevamos la representación comercial en exclusiva para España de diferentes productos de construcción, con la ventaja que damos cobertura técnica para los proyectos con este tipo de solución estructural."

  [params.estructuras.punto6]
    enable = true
    title = "SERVICIOS DE OFICINA TÉCNICA"
    paragraph = "Nos desplazamos al centro de trabajo del cliente."

  [params.catchphrase]
    enable = true
    phrase = " Decide, lidera, disfruta y cumple "
    subtext = "Nuestro lema"

  [params.business]
    enable = true
    title = "Business & Corporate"
    subtitle = "Consultoría técnica y empresarial"
    paragraph = "Somos una empresa internacional dedicada a la consultoría de servicios con carácter multidisciplinar. Nuestro cometido es ofrecer una diversidad de soluciones encaminadas a ayudar a nuestros clientes a alcanzar la excelencia empresarial de forma sostenible y continuada en el tiempo. Les ayudamos a ser eficientes y competitivos, a aprovechar las oportunidades y les dotamos de entornos de seguridad para una mejor toma de decisiones.Nuestras capacidades permiten adaptar los modos de trabajo globales de acuerdo a las necesidades particulares que nuestros clientes precisan y, de esta forma, abarcamos las líneas estratégicas de la empresa."
    p1 = "Ofrecemos una perspectiva basada en las ideas, en la innovación y en la experiencia."
    p2 = "El conocimiento es nuestra seña de identidad, y el compartirlo, lo que nos hace únicos."
    p3 = "Somos expertos en optimización de RRHH y en Gestionar y Formar Talento."
    p4 = "Presumimos de utilizar la Transparencia como Modelo de Relación con Nuestros Clientes."

  [params.business.advantages]
    enable = true
    title = "QUÉ OFRECEMOS"

  [params.business.advantages.punto1]
    enable = true
    title = "Disminucion del riesgo"
    paragraph = "Se analizan las decisiones con datos objetivos como apoyo a la experiencia e intuición directiva. Se analizan las tendencias de mercado y movimientos de competidores de forma sistemática."

  [params.business.advantages.punto2]
    enable = true
    title = "Operaciones eficientes"
    paragraph = "Optimización del modelo operativo con una optimización de los recursos y mejora de costes operativos. Movilidad Geográfica. Soluciones Flexibles según necesidades. Integración en los equipos."

  [params.business.advantages.punto3]
    enable = true
    title = "Planificación estratégica"
    paragraph = "Desarrollar una planificación estratégica dentro de la empresa, donde se analice factores internos y externos de la industria, mercado, competencia, producto, reestructura de la misión, visión, valores, objetivos, etc."

  [params.business.advantages.punto4]
    enable = true
    title = "Agilidad en el mercado"
    paragraph = "Se reducen plazos en la adaptación al cambio ya que las empresas se preparan para detectar tendencias, diseñar planes e implantarlos con eficiencia y obtener resultados positivos de forma sistemática."

  [params.stats.punto1]
    enable = true
    counter = "446760"
    title = "HORAS DE EXPERIENCIA"

  [params.stats.punto2]
    enable = true
    counter = "1000"
    title = "PROYECTOS REALIZADOS"

  [params.stats.punto3]
    enable = true
    counter = "51"
    title = "AÑOS DE EXPERIENCIA"

  [params.stats.punto4]
    enable = true
    counter = "500"
    title = "CONTACTOS PROFESIONALES"

  [params.about_us]
    enable = true
    title = "Sobre Nosotros"
    subtitle = "Un equipo de Profesionales"
    p1 = "Somos un equipo de profesionales dedicado al outsourcing técnico directo. Nuestro lema es “decide, lidera, disfruta y cumple” expresión que sintetiza nuestros valores de ofrecer unos servicios de la mayor calidad, cumpliendo rigurosamente con los hitos marcados por nuestros clientes, con los que creamos una relación basada en la confianza y el compromiso."
    p2 = "Estructuras Civiles y Business & Corporate, son nuestras dos líneas de negocio a través de las cuales ofrecemos servicios personalizados de ingeniería y consultoría técnica y empresarial."
    p3 = "Estamos especializados en Grandes Prefabricados de Hormigón para grandes superficies comerciales e industriales, edificación dotacional y residencial, obra civil y marítima."
    p4 = "Somos Ingenieros Industriales con más de 20 años de experiencia trabajando en el sector de la construcción y en el sector industrial."
    p5 = "Hemos trabajado con los principales grupos privados españoles (Inditex, Repsol, Cepsa, BSCH, Cruz Roja, Sacyr, Acciona, Dragados, ACS y Ferrovial…) e internacionales (Ikea, Sonae, Petrogal, Grupo Mota-Engil, Odebrecht,…) en la gestión de grandes obras en la Península Ibérica."

  [params.team]
    enable = true
    title = "Nuestro equipo"

  [params.team.member1]
    enable = true
    name = "Jaime Lorenzo"
    job = "Jefe de Operaciones "
    description = "Mi trayectoria profesional, de más de 22 años en áreas claves de la dirección, me permiten diseñar soluciones para todo tipo de clientes y cubriendo todas las necesidades requeridas. Soy un gran conocedor del sector del prefabricado de hormigón y poseo una dilatada experiencia en la gestión de grandes proyectos."
    linkedin = "https://es.linkedin.com/in/jaime-alberto-lorenzo-mateo-230a1587"

  [params.team.member2]
    enable = true
    name = "Ángeles Eirin"
    job = "Dirección Técnica-Comercial "
    description = "He participado en el desarrollo de grandes estructuras prefabricadas de edificios comerciales e industriales de multinacionales españolas y extranjeras. Más de 1.000 obras realizadas en los más de 29 años de experiencia, desde distintos puestos de responsabilidad, abarcando todos los procesos, de inicio a fin de obra."
    linkedin = "https://es.linkedin.com/in/angeles-eirin-barrio-8b034346"

  [params.clients]
    enable = true
    title = "Confían en nosotros"


  [params.footer.text]
    enable = true
    title = "Outsourcing t&eacute;cnico"
    paragraph = "A través de nuestras dos líneas de negocio, Estructuras Civiles y Business & Corporate, ofrecemos servicios personalizados de ingeniería y consultoría técnica y empresarial."

  [params.feature]
    enable = true
    title = "We believe in great ideas"
    content = "Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Maecenas faucibus mollis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."

  [params.feature.button]
    caption = "View Works"
    url = "#"

  [params.call]
    enable = true
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.contact]
    enable = true
    title = "Contacto"
    subtitle = "Visitanos o cubre el formulario para contactar con nosotros."

  [params.contact.form]
    name = "Nombre"
    email = "Email"
    company = "Compañia"
    message = "Comentarios"
    button = "Enviar"




  [params.contact.gmaps]
    title = "We Also Count in Google Maps"


  [privacy]

    [privacy.googleAnalytics]
        disable = true
    [privacy.youtube]
        disable = true
